#!/usr/bin/env bash

clear

file=$1

if [[ $file =~ .+\.c$ ]]; then
	#echo C file
	out=${file/%.c}.out
	#echo $out
	gcc -o $out $file -lm
	if [ $? -eq 0 ]; then
		if [[ ${out:0:1} = / ]]; then
			$out
		else
			./$out
		fi
	fi

elif [[ $file =~ .+\.cpp$ ]]; then
	#echo C++ file
	out=${file/%.cpp}.out
	#echo $out
	g++ -o $out $file
	if [ $? -eq 0 ]; then
		if [[ ${out:0:1} = / ]]; then
			$out
		else
			./$out
		fi
	fi

elif [[ $file =~ .+\.py$ ]]; then
	#echo Python file
	python $file

elif [[ $file =~ .+\.tex ]]; then
	pdflatex $file
	if [ $? -eq 0 ]; then
		qpdfview ${file/%.tex}.pdf &
	fi

elif [[ $file =~ .+\.java ]]; then
	java $file

else
	echo Not a C/C++/Python/LaTex source file

fi
