#!/usr/bin/env bash

clear

file=$1
browser=firefox

if [[ $file =~ .+\.c$ ]]; then
	#echo C file
	out=${file/%.c}.out
	#echo $out
	gcc -o $out $file -lm
	if [ $? -eq 0 ]; then
		if [[ ${out:0:1} = / ]]; then
			$out
		else
			./$out
		fi
	fi

elif [[ $file =~ .+\.cpp$ ]]; then
	#echo C++ file
	out=${file/%.cpp}.out
	#echo $out
	g++ -o $out $file
	if [ $? -eq 0 ]; then
		if [[ ${out:0:1} = / ]]; then
			$out
		else
			./$out
		fi
	fi

elif [[ $file =~ .+\.java ]]; then
	javac $file
	if [ $? -eq 0 ]; then
		java ${file/%.java}
	fi

elif [[ $file =~ .+\.py$ ]]; then
	#echo Python file
	python $file

elif [[ $file =~ .+\.pl$ ]]; then
	#echo Perl file
	perl $file

elif [[ $file =~ .+\.tex$ ]]; then
	pdflatex $file
	if [ $? -eq 0 ]; then
		qpdfview ${file/%.tex}.pdf &
	fi

elif [[ $file =~ .+\.html$ ]]; then
	$browser $file

else
	echo "Not a C/C++/Python/Perl/LaTex/HTML source file"

fi
